### PR TITLE
fix: permanently broken date & time tests

### PR DESCRIPTION
**Pull request by tina80lvl**
Fixes: https://github.com/googleapis/python-spanner-django/issues/472

### CODE REVIEW

**Comment by tina80lvl** [comment]
@googlebot I signed it!

**Comment by IlyaFaer** [comment]
@googlebot I consent.

**Review by mf2199 — APPROVED** [review]
Approving for now, but this PR may later be superseded by #521 that reworks both types and unit tests files.

**Comment by tina80lvl** [comment]
@googlebot I consent.

**Comment by mf2199** [comment]
@googlebot I consent.

**Review by IlyaFaer — APPROVED** [review]

**Pull request merged**
