### PR TITLE
refactor!: erase dbapi directory and all the related tests

### PR DESCRIPTION
**Pull request by IlyaFaer**
BREAKING CHANGE: all the connection API related code was moved into the [original Cloud Spanner client repository](https://github.com/googleapis/python-spanner/tree/master/google/cloud/spanner_dbapi). With this PR the whole `dbapi` directory is erased from this repository.

The dependency on `google-cloud-spanner` of this API is bumped to 2.0.0.

### CODE REVIEW

**Comment by IlyaFaer** [comment]
@c24t , system tests on emulator has failed, as there are no system tests at all now. Should we disable the workflow?

**Review by c24t — APPROVED** [review]
> @c24t, system tests on emulator has failed, as there are no system tests at all now. Should we disable the workflow?

I think so, and the deletion LGTM.

**Comment by IlyaFaer** [comment]
@c24t, unit tests are not able to install `google-cloud-spanner` >= 2.0.0 somewhy, though I see it is released.

**Comment by c24t** [comment]
> @c24t, unit tests are not able to install `google-cloud-spanner` >= 2.0.0 somewhy, though I see it is released.

Looks like this is because they dropped support for 3.5, fix in #557.

**Comment by IlyaFaer** [comment]
@c24t, as we don't actually have unit tests now, we can just comment out these nox sessions until better times.

**Comment by c24t** [comment]
@IlyaFaer to follow up on this PR with another change that re-enables django system tests against the emulator.

**Pull request merged**
