### PR TITLE
add .kokoro for CI on Google Cloud

### LINKED ISSUE #289: tests: move builds from Travis to Kokoro on Google Cloud Build
Let's look at moving to Kokoro which we can get on Google Cloud infrastructure. Travis CI is slow, pricey (costs me about $400/month), throttled.

### PR DESCRIPTION
**Pull request by odeke-em**
Updates #289

### CODE REVIEW

**Comment by odeke-em** [comment]
Kindly /cc-ing @busunkim96

**Comment by busunkim96** [comment]
@odeke-em

It looks like the job is failing because `build.sh` isn't executable:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"github/python-spanner-django/.kokoro/build.sh\": permission denied": unknown.
```

**Comment by odeke-em** [comment]
>It looks like the job is failing because build.sh isn't executable:

@busunkim96 I see, thank you! I've made all the .sh files in this PR executable.

**Comment by odeke-em** [comment]
Presubmit check passed, now I'll start the PR to test the various DJANGO_TEST_APPS

**Pull request merged**
