### PR TITLE
chore: migrate to main branch

### LINKED ISSUE #705: Migrate to main branch
Contributing to https://github.com/googleapis/google-cloud-python/issues/10579, switching the default branch to `main` branch. Also replacing all occurrences of `master` to `main`.

### PR DESCRIPTION
**Pull request by dandhlee**
Fixes #705.

### CODE REVIEW

**Review by tseaver — APPROVED** [review]

**Comment by parthea** [comment]
Hi @asthamohta, Please could you review/approve?

**Review by parthea — APPROVED** [review]

**Comment by parthea** [comment]
You'll need to modify [this line](https://github.com/googleapis/python-spanner-django/blob/main/.github/.OwlBot.lock.yaml#L9) to `0ffe3bdd6c7159692df5f7744da74e5ef19966288a6bf76023e8e04e0c424d7d` instead of `82d046d572a11b84d64d4b9af93ad55a1b6a4854917504ba7557acdfce907dde` in order to get the latest templated files.

**Comment by parthea** [comment]
@googlebot I consent.

**Review by parthea — APPROVED** [review]

**Comment by parthea** [comment]
This is ready for review.

**Review by asthamohta — APPROVED** [review]

**Pull request merged**
