### PR TITLE
[WIP] Use django/django in build script

### PR DESCRIPTION
**Pull request by FirePing32**
fixes: #485 

WIP: A new adaption of #527

### CODE REVIEW

**Comment by prakhargurunani** [comment]
@googlebot I signed it!

**Comment by prakhargurunani** [comment]
@c24t Although I am still working on this, shouldn't we add a `commitment.config.js` to validate commits ?

**Comment by c24t** [comment]
> shouldn't we add a `commitment.config.js` to validate commits ?

There's a [googleapis checker for this](https://github.com/googleapis/repo-automation-bots/tree/master/packages/conventional-commit-lint), AFAIK this is configured the same way for all repos in the org. You can see [the check in action on this PR](https://github.com/googleapis/python-spanner-django/pull/561/checks?check_run_id=1481661810) above.

image

**Comment by c24t** [comment]
FYI you can open PRs as drafts if they're WIP and not ready for review: https://github.blog/2019-02-14-introducing-draft-pull-requests/.

**Comment by c24t** [comment]
Closing as inactive. To fix #485 we need to patch django in tests (or host our own patched version of django), not just s/timgraham/django/.

**Pull request closed without merging**
