### PR TITLE
test: Performance Testing

### PR DESCRIPTION
**Pull request by asthamohta**
Comparing the following functions for Django vs Spanner :
1) Insert one row with fetch after  
2) read one row                 
3) insert many rows                 
4) select many rows                
5) insert many rows with mutations

### CODE REVIEW

**Comment by asthamohta** [comment]
Average timing from running the test case 50 times along with Standard Deviation and Error

Average: 
                                                              Django   Spanner
insert_one_row_with_fetch_after     0.47840  0.00835
read_one_row                                     0.46035  0.46130
insert_many_rows                              1.47185   0.08845
select_many_rows                             0.46195  0.46365
insert_many_rows_with_mutations  0.80665  0.01245

Standard Deviation: 
                                                            Django      Spanner
insert_one_row_with_fetch_after    0.002828  0.000778
read_one_row                                    0.001061  0.000424
insert_many_rows                              0.016334  0.002051
select_many_rows                             0.003465  0.000778
insert_many_rows_with_mutations  0.006859  0.000212

Error: 
                                                            Django   Spanner
insert_one_row_with_fetch_after    0.00200  0.00055
read_one_row                                    0.00075  0.00030
insert_many_rows                             0.01155   0.00145
select_many_rows                             0.00245  0.00055
insert_many_rows_with_mutations  0.00485  0.00015

**Comment by asthamohta** [comment]
Average timing after running the performance test 50 times along with standard deviation and error:

Average: 
                                                            Django     Spanner
insert_one_row_with_fetch_after    0.47840  0.00835
read_one_row                                    0.46035  0.46130
insert_many_rows                              1.47185   0.08845
select_many_rows                             0.46195   0.46365
insert_many_rows_with_mutations  0.80665  0.01245

Standard Deviation: 
                                                             Django      Spanner
insert_one_row_with_fetch_after    0.002828  0.000778
read_one_row                                    0.001061   0.000424
insert_many_rows                              0.016334  0.002051
select_many_rows                             0.003465  0.000778
insert_many_rows_with_mutations  0.006859  0.000212

Error: 
                                                             Django    Spanner
insert_one_row_with_fetch_after     0.00200  0.00055
read_one_row                                     0.00075  0.00030
insert_many_rows                              0.01155   0.00145
select_many_rows                              0.00245  0.00055
insert_many_rows_with_mutations  0.00485  0.00015

**Review by vi3k6i5 — COMMENTED** [review]
some nit fixes.

**Review by vi3k6i5 — APPROVED** [review]
LGTM

**Pull request merged**
